OUTPUT_DIR: 'results/bdd_fb600_time_lr2x_aug'
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: FBNet
    DOMAIN_SCC: True
    NUM_EXPERTS: 4 
  FBNET:
    ARCH: "default"
    BN_TYPE: "bn"
    WIDTH_DIVISOR: 8
    DW_CONV_SKIP_BN: True
    DW_CONV_SKIP_RELU: True
  RPN:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (16, )
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 200
    RPN_HEAD: FBNet.rpn_head
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 6
    FEATURE_EXTRACTOR: FBNet.roi_head
    NUM_CLASSES: 11
DATASETS:
  TRAIN: ("domain_bdd100k_cocofmt_train", )
  TEST: ("domain_bdd100k_cocofmt_val",)
SOLVER:
  BASE_LR: 0.12
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 128  # for 8GPUs
# TEST:
#   IMS_PER_BATCH: 8
INPUT:
  BRIGHTNESS: 0.1
  CONTRAST: 0.1
  SATURATION: 0.1
  HUE: 0.1

  MIN_SIZE_TRAIN: (480, 540, 600, 660, 720)
  MAX_SIZE_TRAIN: 1080
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1080
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]
