OUTPUT_DIR: './results/fbnet-bdd-lr2x-aug2_planb'
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: FBNet
  FBNET:
    ARCH: "default"
    BN_TYPE: "bn"
    WIDTH_DIVISOR: 8
    DW_CONV_SKIP_BN: True
    DW_CONV_SKIP_RELU: True
  RPN:
    ANCHOR_SIZES: (16, 32, 64, 128, 256)
    ANCHOR_STRIDE: (16, )
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 100
    
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 6
    FEATURE_EXTRACTOR: FBNet.roi_head
    NUM_CLASSES: 11
# DATALOADER:
#   NUM_WORKERS: 2
DATASETS:
  TRAIN: ("bdd100k_cocofmt_train",)
  #TEST: ("bdd100k_cocofmt_train",)
  #TEST: ("bdd100k_cocofmt_val",)
  TEST: ("bdd100k_cocofmt_train_time1",)
SOLVER:
  BASE_LR: 0.12
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 128  # for 8GPUs
# TEST:
#   IMS_PER_BATCH: 8
INPUT:
  BRIGHTNESS: 0.4 
  CONTRAST: 0.4
  SATURATION: 0.4
  HUE: 0.4
  MIN_SIZE_TRAIN: (240, 280, 320, 360, 400)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 320
  MAX_SIZE_TEST: 640
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]
