OUTPUT_DIR: './results/pland_ft_time1'
MODEL:
  WEIGHT: '../models/bdd_fb_aug2_lr2.model'
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: FBNet
  FBNET:
    ARCH: "default"
    BN_TYPE: "bn"
    WIDTH_DIVISOR: 8
    DW_CONV_SKIP_BN: True
    DW_CONV_SKIP_RELU: True
  RPN:
    ANCHOR_SIZES: (16, 32, 64, 128, 256)
    ANCHOR_STRIDE: (16, )
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 100
    
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 6
    FEATURE_EXTRACTOR: FBNet.roi_head
    NUM_CLASSES: 11
# DATALOADER:
#   NUM_WORKERS: 2
DATASETS:
  TRAIN: ("bdd100k_cocofmt_train_time1",) # 5027
  #TEST: ("bdd100k_cocofmt_train",)
  #TEST: ("bdd100k_cocofmt_val",)
  TEST: ("bdd100k_cocofmt_val_time1",)
SOLVER:
  BASE_LR: 0.002 #0.12 * 0.1 / 2 for 4 GPUs
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  STEPS: (2400, 3200)
  MAX_ITER: 3600 # for nearly 75 epochs
  WARMUP_ITERS: 200
  #IMS_PER_BATCH: 128  # 128 for 8GPUs
  IMS_PER_BATCH: 64  # 128 for 8GPUs
  CHECKPOINT_PERIOD: 400
# TEST:
#   IMS_PER_BATCH: 8
INPUT:
  BRIGHTNESS: 0.4 
  CONTRAST: 0.4
  SATURATION: 0.4
  HUE: 0.4
  MIN_SIZE_TRAIN: (240, 280, 320, 360, 400)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 320
  MAX_SIZE_TEST: 640
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]
